// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nerf.proto

/*
Package nerf is a generated protocol buffer package.

It is generated from these files:
	nerf.proto

It has these top-level messages:
	PingRequest
	PingResponse
	Request
	Response
	Notify
*/
package nerf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingRequest struct {
	Data             *int64  `protobuf:"varint,1,req,name=data" json:"data,omitempty"`
	Login            *string `protobuf:"bytes,2,req,name=login" json:"login,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PingRequest) GetData() int64 {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return 0
}

func (m *PingRequest) GetLogin() string {
	if m != nil && m.Login != nil {
		return *m.Login
	}
	return ""
}

type PingResponse struct {
	Data             *int64 `protobuf:"varint,1,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PingResponse) GetData() int64 {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return 0
}

type Request struct {
	Login            *string `protobuf:"bytes,1,req,name=login" json:"login,omitempty"`
	Token            *string `protobuf:"bytes,2,req,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Request) GetLogin() string {
	if m != nil && m.Login != nil {
		return *m.Login
	}
	return ""
}

func (m *Request) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

type Response struct {
	Config           *string  `protobuf:"bytes,1,req,name=config" json:"config,omitempty"`
	ClientIP         *string  `protobuf:"bytes,2,req,name=clientIP" json:"clientIP,omitempty"`
	Teams            []string `protobuf:"bytes,3,rep,name=teams" json:"teams,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Response) GetConfig() string {
	if m != nil && m.Config != nil {
		return *m.Config
	}
	return ""
}

func (m *Response) GetClientIP() string {
	if m != nil && m.ClientIP != nil {
		return *m.ClientIP
	}
	return ""
}

func (m *Response) GetTeams() []string {
	if m != nil {
		return m.Teams
	}
	return nil
}

type Notify struct {
	Login            *string `protobuf:"bytes,1,req,name=login" json:"login,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Notify) Reset()                    { *m = Notify{} }
func (m *Notify) String() string            { return proto.CompactTextString(m) }
func (*Notify) ProtoMessage()               {}
func (*Notify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Notify) GetLogin() string {
	if m != nil && m.Login != nil {
		return *m.Login
	}
	return ""
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "nerf.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "nerf.PingResponse")
	proto.RegisterType((*Request)(nil), "nerf.Request")
	proto.RegisterType((*Response)(nil), "nerf.Response")
	proto.RegisterType((*Notify)(nil), "nerf.Notify")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Server service

type ServerClient interface {
	Connect(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Disconnect(ctx context.Context, in *Notify, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type serverClient struct {
	cc *grpc.ClientConn
}

func NewServerClient(cc *grpc.ClientConn) ServerClient {
	return &serverClient{cc}
}

func (c *serverClient) Connect(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/nerf.Server/Connect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) Disconnect(ctx context.Context, in *Notify, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/nerf.Server/Disconnect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := grpc.Invoke(ctx, "/nerf.Server/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Server service

type ServerServer interface {
	Connect(context.Context, *Request) (*Response, error)
	Disconnect(context.Context, *Notify) (*google_protobuf.Empty, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

func RegisterServerServer(s *grpc.Server, srv ServerServer) {
	s.RegisterService(&_Server_serviceDesc, srv)
}

func _Server_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nerf.Server/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).Connect(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Notify)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nerf.Server/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).Disconnect(ctx, req.(*Notify))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nerf.Server/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Server_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nerf.Server",
	HandlerType: (*ServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _Server_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _Server_Disconnect_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Server_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nerf.proto",
}

func init() { proto.RegisterFile("nerf.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x86, 0x5b, 0x40, 0x5a, 0xc7, 0x6a, 0xe2, 0xc4, 0x34, 0x04, 0x13, 0x43, 0xf6, 0xd4, 0x78,
	0x80, 0xc4, 0x68, 0x7c, 0x00, 0xf5, 0xe0, 0xc5, 0x34, 0xe8, 0x0b, 0x20, 0x0e, 0x64, 0x23, 0xdd,
	0x41, 0xd8, 0x9a, 0xf4, 0x59, 0x7c, 0x59, 0xc3, 0x2e, 0x10, 0x0e, 0xbd, 0xcd, 0x3f, 0xcc, 0xff,
	0xcd, 0xf0, 0x2f, 0x80, 0xa2, 0xa6, 0x88, 0xeb, 0x86, 0x35, 0xa3, 0xd7, 0xd5, 0xe1, 0x75, 0xc9,
	0x5c, 0x56, 0x94, 0x98, 0xde, 0xe7, 0xbe, 0x48, 0x68, 0x57, 0xeb, 0x83, 0x1d, 0x11, 0x8f, 0x70,
	0xb6, 0x95, 0xaa, 0x4c, 0xe9, 0x67, 0x4f, 0xad, 0x46, 0x04, 0xef, 0x2b, 0xd3, 0x59, 0x30, 0x8f,
	0x9c, 0x8d, 0x9b, 0x9a, 0x1a, 0xaf, 0xe0, 0xa4, 0xe2, 0x52, 0xaa, 0xc0, 0x89, 0x9c, 0xcd, 0x69,
	0x6a, 0x85, 0x10, 0xb0, 0xb2, 0xc6, 0xb6, 0x66, 0xd5, 0xd2, 0x31, 0xa7, 0x78, 0x80, 0xc5, 0x00,
	0x1e, 0x21, 0xf3, 0x09, 0xa4, 0xeb, 0x6a, 0xfe, 0xa6, 0x11, 0x6d, 0x84, 0xf8, 0x80, 0xe5, 0x88,
	0x5d, 0x83, 0x9f, 0xb3, 0x2a, 0x64, 0xd9, 0x1b, 0x7b, 0x85, 0x21, 0x2c, 0xf3, 0x4a, 0x92, 0xd2,
	0xaf, 0xdb, 0xde, 0x3c, 0x6a, 0x43, 0xa5, 0x6c, 0xd7, 0x06, 0x6e, 0xe4, 0x1a, 0x6a, 0x27, 0xc4,
	0x0d, 0xf8, 0x6f, 0xac, 0x65, 0x71, 0x38, 0x7e, 0xcb, 0xdd, 0xdf, 0x1c, 0xfc, 0x77, 0x6a, 0x7e,
	0xa9, 0xc1, 0x5b, 0x58, 0x3c, 0xb1, 0x52, 0x94, 0x6b, 0x3c, 0x8f, 0x4d, 0x9e, 0xfd, 0x6f, 0x84,
	0x17, 0x83, 0xb4, 0xe7, 0x89, 0x19, 0xde, 0x03, 0x3c, 0xcb, 0x36, 0xef, 0xc7, 0x57, 0xf6, 0xbb,
	0x5d, 0x14, 0xae, 0x63, 0x1b, 0x7d, 0x3c, 0x44, 0x1f, 0xbf, 0x74, 0xd1, 0x8b, 0x19, 0x26, 0xe0,
	0x75, 0xe9, 0xe1, 0xa5, 0x9d, 0x9f, 0x3c, 0x41, 0x88, 0xd3, 0xd6, 0xb0, 0xe6, 0x3f, 0x00, 0x00,
	0xff, 0xff, 0x4d, 0xc6, 0x90, 0x2c, 0xd7, 0x01, 0x00, 0x00,
}
