name: Validation
on:
  pull_request:
    paths:
      - '.github/workflows/check.yml'
      - '**.go'
jobs:
  check:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-gofmt1.16-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gofmt1.16-
      - name: Install dependencies
        run: sudo apt install libappindicator3-dev gir1.2-appindicator3-0.1 -y
      - name: Run make check
        run: make check
