name: Validation
on: pull_request

jobs:
  check:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: sudo apt install libappindicator3-dev gir1.2-appindicator3-0.1 -y
      - name: Run golines
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go get -u github.com/segmentio/golines
          golines -w ./
      - name: Run go fmt
        run: test -z "$(go fmt ./...)"
      - name: Run go fix
        run: test -z "$(go fix ./...)"
      - name: Run go mod tidy
        run: test -z "$(go mod tidy ./...)"
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
