name: Validation
on:
  pull_request:
    paths:
      - '.github/workflows/linters.yml'
      - '**.go'
jobs:
  check:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: sudo apt install libappindicator3-dev gir1.2-appindicator3-0.1 -y
      - name: Install goimports
        run: |
          go get golang.org/x/tools/cmd/goimports
          go build golang.org/x/tools/cmd/goimports
      - name: Install golines
        run: go get -u github.com/segmentio/golines
      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh
      - name: Run make check
        run: make check
